/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        nudge: {
          blue: '#2E62F6',
          'blue-light': '#507DFE',
          'blue-container': '#EBF1FF',
          'blue-container-dark': '#1F263B',
          'active-nav-blue': '#4579F5',
          cream: '#FAF7F2',
          card: '#FFFFFF',
          'card-dark': '#22201D',
          parchment: '#F4EFE6',
          'parchment-dark': '#2A2723',
          'surface-variant': '#F2EFE8',
          'surface-variant-dark': '#2A2723',
          border: '#EDE8DF',
          'border-dark': '#3C3730',
          'outline-variant': '#DFD9CE',
          'outline-variant-dark': '#49433B',
          dark: '#181614',
          'text-primary': '#1C1A17',
          'text-secondary': '#756F67',
          'text-muted': '#A39D93',
          'text-primary-dark': '#EDE8DF',
          'text-secondary-dark': '#9F988D',
          'text-muted-dark': '#756F65',
          sage: '#E2EBE2',
          peach: '#FFFFECE0',
          lavender: '#EDE9F7',
          important: '#FA541C',
          'toast-bg': '#1F1E1B',
          // Category tag colors
          'tag-personal-bg': '#EBF1FF',
          'tag-personal-text': '#2E62F6',
          'tag-personal-bg-dark': '#1E283C',
          'tag-personal-text-dark': '#96B7FF',
          'tag-shopping-bg': '#FFF0E6',
          'tag-shopping-text': '#D45512',
          'tag-shopping-bg-dark': '#382318',
          'tag-shopping-text-dark': '#FFAB78',
          'tag-home-bg': '#EFF7EE',
          'tag-home-text': '#2A7E35',
          'tag-home-bg-dark': '#1D2F22',
          'tag-home-text-dark': '#A2E4AA',
          'tag-work-bg': '#F3EEF9',
          'tag-work-text': '#6B48B8',
          'tag-work-bg-dark': '#2E223D',
          'tag-work-text-dark': '#D2B3F9',
          'tag-other-bg': '#F5F1EB',
          'tag-other-text': '#6D635C',
          'tag-other-bg-dark': '#2D2A26',
          'tag-other-text-dark': '#DDD7CE',
        },
      },
      fontFamily: {
        serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        sans: ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
      },
      borderRadius: {
        'card': '18px',
        'hero': '24px',
        'badge': '12px',
        'input': '14px',
        'pill': '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      boxShadow: {
        'soft': '0 2px 10px rgba(0, 0, 0, 0.03), 0 1px 3px rgba(0, 0, 0, 0.02)',
        'float': '0 8px 30px rgba(0, 0, 0, 0.08), 0 2px 8px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
}
